/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;

import UserInterface.Immunization.ImmunizationManagement;
import UserInterface.Rule.RuleManagement;
import UserInterface.School.SchoolManagement;
import daycareproject.Classroom;
import daycareproject.Course;
import daycareproject.Person;
import daycareproject.Rule;
import daycareproject.School;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author dingt
 */
public class MainWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form MainWorkArea
     */
    private School school;
    public MainWorkArea(JSplitPane container, School school) {
        initComponents();
        this.container=container;
        this.school=school;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JSplitPane();
        PanelLeft = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                ImageIcon img=new ImageIcon(getClass().getResource("../cloud.jpg"));
                g.drawImage(img.getImage(),0,0,getWidth(),getHeight(),null);
            }
        };
        btnSingle = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanelRight = new javax.swing.JPanel();

        btnSingle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSingle.setText("School ");
        btnSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingleActionPerformed(evt);
            }
        });

        btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn.setText("prepare");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Immunization");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Rules");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLeftLayout = new javax.swing.GroupLayout(PanelLeft);
        PanelLeft.setLayout(PanelLeftLayout);
        PanelLeftLayout.setHorizontalGroup(
            PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLeftLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSingle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelLeftLayout.setVerticalGroup(
            PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLeftLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnSingle)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(66, 66, 66)
                .addComponent(jButton2)
                .addGap(68, 68, 68)
                .addComponent(btn)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        container.setLeftComponent(PanelLeft);

        PanelRight.setLayout(new java.awt.CardLayout());
        container.setRightComponent(PanelRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingleActionPerformed
        // TODO add your handling code here:
        SchoolManagement smg = new SchoolManagement(school,PanelRight);
        PanelRight.add("SchoolManagement",smg);
        CardLayout layout = (CardLayout)PanelRight.getLayout();
        layout.next(PanelRight);
    }//GEN-LAST:event_btnSingleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ImmunizationManagement imh = new ImmunizationManagement(PanelRight,school);
        PanelRight.add("MainWorkArea",imh);
        CardLayout layout = (CardLayout)PanelRight.getLayout();
        layout.next(PanelRight);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RuleManagement rmi = new RuleManagement(school,PanelRight);
        PanelRight.add("RuleManagement",rmi);
        CardLayout layout = (CardLayout)PanelRight.getLayout();
        layout.next(PanelRight);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
         for(Person p: school.getStudentlist())
            p.setAge(p.getAge()+1);
        for(Person p: school.getTeacherlist())
            p.setAge(p.getAge()+1);
        if(school.getRuleTime().after(school.getLastPrepare())){
            System.out.println("need prepare");
            school.setLastPrepare(new Date());
             for(Classroom cl:school.getClassroomlist()){
                cl.getCourselist().clear();
            }
             school.getCourselist().clear();
             for(Rule r: school.getRulelist()){
                school.addCourse("Course 1", 4.0, r);
             }
            
        }
        else{
            for(Course c: school.getCourselist()){
                c.getStudentlist().clear();
                c.setTeacher(null);
                c.setClassroom(null);
            }
            for(Classroom cl:school.getClassroomlist()){
                cl.getCourselist().clear();
            }
        }
       Preparation rmi = new Preparation(school,PanelRight);
        PanelRight.add("Preparation",rmi);
        CardLayout layout = (CardLayout)PanelRight.getLayout();
        layout.next(PanelRight);
    }//GEN-LAST:event_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLeft;
    private javax.swing.JPanel PanelRight;
    private javax.swing.JButton btn;
    private javax.swing.JButton btnSingle;
    private javax.swing.JSplitPane container;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
